# Database Configuration
spring:
  application:
    name: QueryMe-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT Configuration
queryme:
  app:
    jwtSecret: ${JWT_SECRET:QueryMeApplicationSecretKeyMustBeLongEnoughForHMACSHA256SignatureAlgorithm}
    jwtExpirationMs: ${JWT_EXPIRATION:86400000}